@startuml get_latest_price
actor User
boundary Server <<router>>
control auth <<middleware>>
control controller <<handler>>
entity dbi
database DB
collections price <<collection>>

User -> Server : http request POST\nget latest price
Server -> auth : verify auth
alt verify successed
    auth --> Server
    Server -> controller : get Price
    controller -> dbi : Find
    dbi -> DB : FindOne
    DB -> price
    DB --> dbi
    dbi --> controller
    controller --> Server : Price data
    Server --> User : http responce/200
else verify failed
    auth --> Server
    Server --> User : http responce/401
end
@enduml